### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by R-carrot** [R-carrot/furima-31916#11]
# URL
https://furima-31916.herokuapp.com/
# BASIC認証
#### username 
admin
#### password 
2222
# 出品者のメール、パスワード
#### email
hoge@hoge
#### password
hoge11
# 購入者のメール、パスワード
#### email
susi@susi
#### password
susi11
# テストカード
#### 番号
4242424242424242
#### 期限
3/35
#### セキュリティコード
123

**Comment by snkw-works** [comment]
@R-carrot さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ログアウト状態のユーザーでも、商品詳細表示ページを閲覧できるよう修正しましょう**
現状、ログアウト状態のユーザーは商品詳細表示ページを閲覧できない状態です。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/117387710-53876e00-af24-11eb-9d2a-ca856558dbd4.png)
